@hostname = http://127.0.0.1:8000

### 获取 JWT Tokens
POST {{hostname}}/users/login/
Content-Type: application/json

{
  "username": "newuser2",
  "password": "newpassword123"
}

###

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1MDg1ODU3LCJpYXQiOjE3MTUwODQwNTcsImp0aSI6ImYwYTVkNmVmODNkODRiMzU4M2EwN2E0NzIzN2NkNWQ2IiwidXNlcl9pZCI6Mn0.QOA8bS4fnn8OCOozoVSgty6QJNsV5Liup5e_c9MkVos

### Publish Goods
POST {{hostname}}/exchange/goods/
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{authToken}}

--WebAppBoundary
Content-Disposition: form-data; name="content"

good job
--WebAppBoundary
Content-Disposition: form-data; name="money"

100
--WebAppBoundary
Content-Disposition: form-data; name="origin_money"

150
--WebAppBoundary
Content-Disposition: form-data; name="send_money"

10
--WebAppBoundary
Content-Disposition: form-data; name="classify"

Electronics
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpeg

< ./resources/example.jpg
--WebAppBoundary--

### Get Goods List
GET {{hostname}}/exchange/goods/list
Authorization: Bearer {{authToken}}

### My Goods
GET {{hostname}}/exchange/goods/mine/
Authorization: Bearer {{authToken}}

### Goods Detail
GET {{hostname}}/exchange/goods/0e299c2029752f6eec4cd3111ff5dd33/
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

### Search Goods
POST {{hostname}}/exchange/search/
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

q=here&method=1&page=1